# Use the following command to run:
# ansible-inventory --graph -i google.cloud.gcp_compute.yaml
#
# Pre-reqs:
# pip install requests google-auth
#
plugin: google.cloud.gcp_compute
regions: # populate inventory with instances in these regions
  - europe-west2
projects: # populate inventory with instances in these projects
  - pcherry-cbcore-trad
filters: [] # apply these filters to the compute instances
service_account_file: ~/Google Drive/Keys/philsa@pcherry-cbcore-trad/service_account.json # the name of the serviceaccount key json file (eg the output of gcloud iam service-accounts keys create ~/key.json --iam-account philsa@pcherry-cbcore-trad.iam.gserviceaccount.com)
auth_kind: serviceaccount # the type of authentication
hostnames:
  # List host by name instead of the default public ip
  - name